version: '3'
services:
  front:
    build:
      context: FRONTEND
      target: prod
    ports:
      - ${FRONT_PORT}:8080
    restart: always

  dbobjects:
    build: DBobjects

  db:
    image: postgres:15.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}