version: '3'
services:
  front:
    build:
      context: FRONTEND
      target: dev
    ports:
      - ${FRONT_PORT}:4200
    restart: always
    volumes:
      - ./FRONTEND/src:/appdev/src

  dbobjects:
    image: maven:3.8.5-openjdk-17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - maven:/root/.m2
      - ./DBobjects:/app
    command: ["mvn", "package"]
    working_dir: /app


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: postgres:15.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  maven: