version: '3.4'
services:
  front:
    build:
      context: FRONTEND
      target: dev
    ports:
      - ${FRONT_PORT}:4200
    restart: always
    volumes:
      - ./FRONTEND/src:/appdev/src

  dbobjects:
    image: maven:3.8.5-openjdk-17
    volumes:
      - maven:/root/.m2
      - ./DBobjects:/app
    command: ["mvn", "install"]
    working_dir: /app

  api:
    image: maven:3.8.5-openjdk-17
    volumes:
      - maven:/root/.m2
      - ./API:/app
    command: ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=prod"]
    working_dir: /app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: postgres:15.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  maven: