version: '3.4'
services:
  front:
    image: fgdou/esir-vehicules-front
    build:
      context: FRONTEND
      target: prod
    restart: always

  dbobjects:
    build: DBobjects

  nginx:
    image: fgdou/esir-vehicules-nginx
    build:
      context: nginx
      target: prod
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - front
      - api

  api:
    image: fgdou/esir-vehicules-api
    build:
      target: prod
      context: API
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
  datahandler:
    image: fgdou/esir-vehicules-datahandler
    build:
      target: prod
      context: DataHandler
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATAHANDLER_UPDATE_ON_STARTUP=${DATAHANDLER_UPDATE_ON_STARTUP}
    depends_on:
      - db

  db:
    image: postgres:15.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}